---
version: '3'

# Ansible Pi Cluster Task Runner Configuration
# This file defines all available tasks for managing the cluster

vars:
  PLAYBOOKS_DIR: playbooks
  INVENTORY: inventories/hosts.yml

tasks:
  # Default task - shows help and available playbooks
  default:
    desc: Show available commands and dynamically discovered playbooks
    silent: true
    cmds:
      - ./scripts/task-default.sh

  # Core management tasks
  install:
    desc: Install project dependencies (Ansible, collections, etc.)
    cmds:
      - ./scripts/task-install.sh

  test:
    desc: Test connectivity to all hosts in escalating order of importance
    cmds:
      - ./scripts/task-test.sh

  clean:
    desc: Cleanup temporary files and cached results
    cmds:
      - ./scripts/task-clean.sh

  list:
    desc: List all available tasks and playbooks
    silent: true
    cmds:
      - ./scripts/task-list.sh

  # Playbook execution tasks
  playbook:
    desc: >-
      Run any playbook with intelligent SSH authentication detection.
      Usage: task playbook -- <playbook-name>
      Examples: task playbook -- 1_deploy-ssh-key
    interactive: true
    cmds:
      - ./scripts/task-playbook.sh {{.CLI_ARGS}}

  play:
    desc: Alias for 'playbook' task
    cmds:
      - task playbook -- {{.CLI_ARGS}}

  all:
    desc: Run all numbered playbooks in sequence with intelligent workflow
    interactive: true
    cmds:
      - ./scripts/task-all.sh
