ubuntu:
  hosts:
    ubuntu-1.local:
      ansible_host: ubuntu-1.local
    ubuntu-2.local:
      ansible_host: ubuntu-2.local
    ubuntu-3.local:
      ansible_host: ubuntu-3.local
    ubuntu-4.local:
      ansible_host: ubuntu-4.local

  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_ssh_common_args: >-
      -o ControlMaster=auto -o ControlPersist=60s
      -o PreferredAuthentications=publickey,password
    ansible_ssh_timeout: 10
    ansible_ssh_retries: 3
