---
ubuntu:
  hosts:
    ubuntu-1:
      ansible_host: ubuntu-1
      tailnet_fallback: ubuntu-1.tailc3d5ed.ts.net
    ubuntu-2:
      ansible_host: ubuntu-2
      tailnet_fallback: ubuntu-2.tailc3d5ed.ts.net
    ubuntu-3:
      ansible_host: ubuntu-3
      tailnet_fallback: ubuntu-3.tailc3d5ed.ts.net
    ubuntu-4:
      ansible_host: ubuntu-4
      tailnet_fallback: ubuntu-4.tailc3d5ed.ts.net

  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_ssh_common_args: >-
      -o ControlMaster=auto -o ControlPersist=60s
      -o PreferredAuthentications=publickey,password
    ansible_ssh_timeout: 10
    ansible_ssh_retries: 3
