---
- name: Test Host Connectivity and SSH Authentication Methods
  hosts: ubuntu
  gather_facts: true  # Enable fact gathering to get ansible_date_time
  vars:
    connection_timeout: 10
    results_dir: /tmp/ansible_connectivity_results

  tasks:
    # Phase 1: Basic network connectivity test
    - name: Test basic network connectivity (port 22)
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: "{{ connection_timeout }}"
      delegate_to: localhost
      register: network_connectivity
      failed_when: false

    - name: Skip host if network unreachable
      ansible.builtin.meta: end_host
      when: network_connectivity.failed

    # Phase 2: Test SSH key authentication (no password fallback)
    - name: Test SSH key authentication
      ansible.builtin.command:
        cmd: >-
          ssh -o BatchMode=yes -o PasswordAuthentication=no
          -o ConnectTimeout={{ connection_timeout }}
          -o StrictHostKeyChecking=no
          {{ ansible_user }}@{{ inventory_hostname }} echo 'ssh_key_works'
      delegate_to: localhost
      register: ssh_key_test
      failed_when: false
      changed_when: false

    # Phase 3: Store connectivity results for script to read
    - name: Ensure results directory exists
      ansible.builtin.file:
        path: "{{ results_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      when: inventory_hostname == groups['ubuntu'][0]

    - name: Store connectivity test results
      ansible.builtin.copy:
        content: |
          # Connectivity test results for {{ inventory_hostname }}
          NETWORK_REACHABLE=true
          SSH_KEYS_WORK={{ 'true' if ssh_key_test.rc == 0 else 'false' }}
          HOST={{ inventory_hostname }}
          ANSIBLE_USER={{ ansible_user }}
          TEST_TIMESTAMP={{ ansible_date_time.epoch | default('0') }}
        dest: "{{ results_dir }}/{{ inventory_hostname }}.env"
        mode: '0644'
      delegate_to: localhost

    # Phase 4: Summary for unreachable hosts (this won't run if connectivity fails)
    - name: Mark unreachable hosts
      ansible.builtin.copy:
        content: |
          # Connectivity test results for {{ inventory_hostname }}
          NETWORK_REACHABLE=false
          SSH_KEYS_WORK=false
          HOST={{ inventory_hostname }}
          ANSIBLE_USER={{ ansible_user }}
          TEST_TIMESTAMP={{ ansible_date_time.epoch | default('0') }}
        dest: "{{ results_dir }}/{{ inventory_hostname }}.env"
        mode: '0644'
      delegate_to: localhost
      when: network_connectivity.failed
