---
- name: Test Connection to Ubuntu Servers
  hosts: ubuntu
  gather_facts: no
  vars: {}
  tasks:
    - name: Check SSH port is open from control node
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 5
      delegate_to: localhost

    - name: Display port check success
      debug:
        msg: "✅ SSH port open on {{ inventory_hostname }}"
